ToDoApp/Models/ErrorViewModel.cs
namespace ToDoApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDoApp/Models/TaskModel.cs
using System.ComponentModel.DataAnnotations;

namespace ToDoApp.Models
{
    public class TaskModel
    {
        [Key]
        public int id { get; set; }
        [Required]
        public string task { get; set; }
        [Required]
        public DateTime dueDAte { get; set; }

        public bool completed { get; set; }

    }
}

ToDoApp/Controllers/AddTaskController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Models;
using ToDoApp.NewFolder;

namespace ToDoApp.Controllers
{
    public class AddTaskController : Controller
    {
        private readonly ApplicationDbContext db;

        public AddTaskController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult addMyTask(TaskModel mytask)
        {
            db.Tasks.Add(mytask);
            db.SaveChanges();
            return RedirectToAction(actionName: "index", controllerName: "Home");
        }
        

    }
}

ToDoApp/Controllers/DeleteController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Models;
using ToDoApp.NewFolder;

namespace ToDoApp.Controllers
{
    public class DeleteController : Controller
    {
        private readonly ApplicationDbContext db;

        public  DeleteController(ApplicationDbContext db)
        {
            this.db = db;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Delete(int? id)
        {
            var task = db.Tasks.Find(id);
            return View(task);
        }
        [HttpPost]
        public IActionResult Delete(TaskModel myTask)
        {
            db.Tasks.Remove(myTask);
            db.SaveChanges();
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

    }
}

ToDoApp/Controllers/EditController.cs
using Microsoft.AspNetCore.Mvc;
using ToDoApp.Models;
using ToDoApp.NewFolder;

namespace ToDoApp.Controllers
{
    public class EditController : Controller
    {
        private ApplicationDbContext db;

        public EditController(ApplicationDbContext db)
        {
            this.db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Edit(int? id)
        {
            var task = db.Tasks.Find(id);
            return View(task);
        }
        [HttpPost]
        public IActionResult Edit(TaskModel mytask)
        {

            db.Tasks.Update(mytask);
            db.SaveChanges();
            return RedirectToAction(actionName: "Index", controllerName: "Home");
        }

    }
}

ToDoApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ToDoApp.Models;
using ToDoApp.NewFolder;

namespace ToDoApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext db;

        //public HomeController(ILogger<HomeController> logger)
        //{
        //    _logger = logger;
        //}

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext db) 
        {
            this._logger = logger;
            this.db = db;
        }

        public IActionResult Index()
        {
            IEnumerable<TaskModel> result = db.Tasks.ToList();
            return View(result);
        }

     
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDoApp/Views/AddTask/Index.cshtml
@{
    ViewData["Title"] = "Add";
}
@model TaskModel


<div class="my-conatainer ">
  <partial name="_Title"/>
    
<form method="post">
      <label>Task</label>
      <input asp-for="task" type="text"/>
      <label>Due date</label>
      <input asp-for="dueDAte" type="date"/>
       <button type="submit"  typ class="btn-add" asp-controller="AddTask"  asp-action="addMyTask">Add task</button>
</form>
</div>

ToDoApp/Views/Delete/Delete.cshtml
@{
    ViewData["Title"] = "Add";
}
@model TaskModel

<div class="my-conatainer ">
  <partial name="_Title"/>

<form method="post">
      <label>Task</label>
      <input asp-for="task" disabled type="text"/>
      <label>Due date</label>
      <input asp-for="dueDAte" disabled type="date"/>
       <button type="submit"  class="btn-add" asp-controller="Delete" asp-action="Delete">Delete task</button>
</form>
</div>

ToDoApp/Views/Edit/Edit.cshtml
@{
    ViewData["Title"] = "Edit";
}
@model TaskModel


<div class="my-conatainer ">
  <partial name="_Title"/>

<form method="post">
      <label>Task</label>
      <input asp-for="task"  type="text"/>
      <label>Due date</label>
      <input asp-for="dueDAte"  type="date"/>
       <button type="submit"   class="btn-add" asp-controller="Edit" asp-action="Edit">Edit task</button>
</form>
</div>

ToDoApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<TaskModel>


<div class="my-conatainer ">

  <partial name="_Title"/>
  @foreach (var task in Model)
    {
          <div class="task">
              <div class="left">
                  <input type="checkbox" checked="@task.completed"/>
                  <h6>@task.task</h6>
              </div>
              <div class="right">
                      <a asp-action="Edit" asp-controller="Edit" asp-route-id="@task.id"><i class="bi bi-pencil-square "></i></a>
                      <a asp-action="Delete" asp-controller="Delete"  asp-route-id="@task.id"><i class="bi bi-trash "></i></a>
              </div>
      </div>
    }
  

  <a class="btn-add" asp-controller="AddTask" asp-action="Index" >Add task</a>
</div>

ToDoApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<body>
   
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ToDoApp/Views/Shared/_Title.cshtml
@using ToDoApp.Functionality;
@{
    CustomDate customDate = DateHandler.GetCustomDate();   
}

<div class="title">
    @customDate.Date<sup>@customDate.sup</sup> @customDate.month @customDate.year
  </div>